# feature types
NOMINAL = 'NOM'
NUMERIC = 'NUM'

# methods
IG = 'INFORMATION_GAIN'
GR = 'GAIN_RATIO'

# evaluation metrics
ACCURACY = 'ACCURACY'
PRECISION = 'PRECISION'
RECALL = 'RECALL'
F1_SCORE = 'F1_SCORE'
